# @package _global_
hp_config:
  activation: ELU
  aug_factor: 1.9518162392981246
  base_num_features: 36
  dropout_rate: 0.034542145854179494
  encoder_type: ConvolutionalEncoder
  initial_lr: 0.014335594043671327
  loss_function: DiceAndCrossEntropyLoss
  lr_scheduler: CosineAnnealingLR
  max_features: 414
  model_scale: 1
  momentum: 0.9675695664154482
  normalization: InstanceNorm
  num_epochs: 1000.0
  optimizer: SGD
  oversample_foreground_percent: 0.6514729501136565
  weight_decay: 0.00011536478537295801
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/cross_eval/Dataset001_BrainTumour/${dataset.name}/3d_fullres/0/incumbent
  sweep:
    dir: output/cross_eval/Dataset001_BrainTumour/${dataset.name}/3d_fullres/0/incumbent
    subdir: fold_${fold}
