# @package _global_
hp_config:
  activation: ReLU
  aug_factor: 2.036928439418862
  base_num_features: 28
  dropout_rate: 0.001024386353296433
  encoder_type: ConvolutionalEncoder
  initial_lr: 0.023363284298761194
  loss_function: DiceAndCrossEntropyLoss
  lr_scheduler: CosineAnnealingLR
  max_features: 455
  model_scale: 1
  momentum: 0.890681433657815
  normalization: InstanceNorm
  num_epochs: 1000.0
  optimizer: SGD
  oversample_foreground_percent: 0.6000102132991876
  weight_decay: 7.936885609464652e-06
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/cross_eval/Dataset009_Spleen/${dataset.name}/3d_fullres/0/incumbent
  sweep:
    dir: output/cross_eval/Dataset009_Spleen/${dataset.name}/3d_fullres/0/incumbent
    subdir: fold_${fold}
