seed: 42
fold: 0
device: cuda

load: null
save: null

pipeline:
  return_if_done: true
  run_training: true
  run_validation: true
  validate_with_best: true
  continue_training: true
  remove_validation_files: true

trainer:
  configuration: 3d_fullres
  fold: ${fold}
  plans_identifier: nnUNetPlans
  pretrained_weights_file: null
  use_compressed_data: false
  export_validation_probabilities: false
  disable_checkpointing: false

hp_config:
  optimizer: SGD
  momentum: 0.99
  initial_lr: 1e-2
  weight_decay: 3e-5
  lr_scheduler: PolyLRScheduler
  oversample_foreground_percent: 0.33
  num_epochs: 1000
  total_epochs: 1000
  enable_deep_supervision: true
  normalization: InstanceNorm 
  n_conv_per_stage_encoder: 2 
  n_conv_per_stage_decoder: 2
  loss_function: DiceAndCrossEntropyLoss

hydra:
  job:
    env_set:
      nnUNet_datasets: /mnt/home/jbecktep/git_projects/MSC-JannisBecktepe-AutoNNUnet/data/nnUNet_datasets
      nnUNet_raw: /mnt/home/jbecktep/git_projects/MSC-JannisBecktepe-AutoNNUnet/data/nnUNet_raw
      nnUNet_preprocessed: /mnt/home/jbecktep/git_projects/MSC-JannisBecktepe-AutoNNUnet/data/nnUNet_preprocessed
      nnUNet_results: /mnt/home/jbecktep/git_projects/MSC-JannisBecktepe-AutoNNUnet/data/nnUNet_results

      nnUNet_n_proc_DA: 30

      OMP_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
  

