defaults:
  - _self_
  - dataset: Dataset002_Heart
  - cluster: local

# We need to specify the fold to obtain all images
# but it does not affect the pre-processing
fold: 0

modality: ${dataset.modality}
img_name_suffix: .nii.gz
gt_name_suffix: .nii.gz
num_workers: 48
window_level: 40
window_width: 400
save_nii: false

voxel_num_thre2d: 100
voxel_num_thre3d: 1000

hydra:
  run:
    dir: output/prepare_medsam2/${dataset.name}/
  sweep:
    dir: output/prepare_medsam2/${dataset.name}/
    subdir: ""   
