# @package _global_
defaults:
  - base
  - _self_
  - cluster: kisski_gpu
  - dataset: Dataset001_BrainTumour

pipeline:
  return_if_done: false

hydra:
  output_subdir: "."
  job_logging:
    stdout: true  
    stderr: true  
  run:
    dir: output/baseline_nas/${dataset.name}/${trainer.configuration}
  sweep:
    dir: output/baseline_nas/${dataset.name}/${trainer.configuration}
    subdir: fold_${fold}     
  job:
    chdir: true
