defaults:
  - _self_
  - base
  - cluster: kisski_gpu
  - dataset: Dataset001_BrainTumour

hydra:
  output_subdir: "."
  job_logging:
    stdout: true  
    stderr: true  
  run:
    dir: output/baseline/${dataset.name}/${trainer.configuration}
  sweep:
    dir: output/baseline/${dataset.name}/${trainer.configuration}
    subdir: fold_${fold}     
  # job:
  #   chdir: true
