defaults:
  - _self_
  - base
  - cluster: kisski_gpu
  - search_space: default
  - dataset: Dataset001_BrainTumour
  - override hydra/sweeper: HyperNEPS

neps_seed: 0

# HPO configuration
min_budget: 4     # Minimum number of epochs
max_budget: 1000  # Maximum number of epochs
eta: 3            # Reduction factor for successive halving
budget: 11_000    # Total budget in epochs

hydra:
  sweeper:
    budget: ${budget}
    budget_variable: hp_config.num_epochs
    search_space: ${search_space}
    sweeper_kwargs:
      min_budget: ${min_budget}
      max_budget: ${max_budget}
      job_array_size_limit: 1   # only one config at a time
      seeds: [0, 1, 2, 3, 4]    # these are the folds in our case
      seed_keyword: fold
      deterministic: true
      optimizer_kwargs:
        fidelity_variable: ${hydra.sweeper.budget_variable}
        min_budget: ${min_budget}
        max_budget: ${max_budget}
        seed: ${neps_seed}
        optimizer:
          _target_: neps.optimizers.multi_fidelity_prior.priorband.PriorBand
          _partial_: true
          budget: ${hydra.sweeper.budget}
          eta: ${eta}
          prior_confidence: medium
          prior_weight_type: geometric
          inc_sample_type: mutation
          inc_style: dynamic
          inc_mutation_rate: 0.5
          inc_mutation_std: 0.25
          model_based: False
          sample_default_first: True
          sample_default_at_target: True
  run:  
    dir: output/prior_band/${dataset.name}/${trainer.configuration}/${neps_seed}
  sweep:
    dir: output/prior_band/${dataset.name}/${trainer.configuration}/${neps_seed}
  job:
    chdir: true
