defaults:
  - _self_
  - base
  - cluster: kisski_gpu
  - search_space: default
  - dataset: Dataset001_BrainTumour
  - override hydra/sweeper: HyperSMAC

smac_seed: 0

# SMAC HPO configuration
n_trials: 402     # Total number of configs
min_budget: 15    # Minimum number of epochs
max_budget: 1000  # Maximum number of epochs
budget: 15000     # Total budget in epochs
eta: 4            # Reduction factor for successive halving
min_trials: 4     # Minimum number of trials per budget to fit the surrogate model

# Number of randomly sampled initial configurations, resulting
# in 30 + 1 = 31 total configurations including the default configs.
# This leads to SMAC's default of 127 * 0.25 = 31 initial configs.
initial_design_configs: 30  

hydra:
  sweeper:
    n_trials: ${n_trials}
    budget: ${budget}
    budget_variable: hp_config.num_epochs
    search_space: ${search_space}
    sweeper_kwargs:
      min_budget: ${min_budget}
      max_budget: ${max_budget}
      job_array_size_limit: 1   # only one config at a time
      seeds: [0, 1, 2, 3, 4]    # these are the folds in our case
      seed_keyword: fold
      deterministic: true
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
          overwrite: true
        scenario:
          seed: ${smac_seed}
          n_trials: ${hydra.sweeper.n_trials}
          use_default_config: true  # this increases the number of initial configs by 1
          min_budget: ${hydra.sweeper.sweeper_kwargs.min_budget}
          max_budget: ${hydra.sweeper.sweeper_kwargs.max_budget}
          deterministic: true
          n_workers: 1
          name: smac_output
          output_directory: output/smac_mf/${dataset.name}/${trainer.configuration}/${smac_seed}
        intensifier:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_intensifier
          _partial_: true
          eta: ${eta}
          n_seeds: 1
        initial_design:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_initial_design
          _partial_: true
          n_configs: ${initial_design_configs}
        config_selector:
          _target_: smac.main.config_selector.ConfigSelector
          _partial_: true
          retrain_after: 1
          min_trials: ${min_trials}
  run:  
    dir: output/smac_mf/${dataset.name}/${trainer.configuration}/${smac_seed}
  sweep:
    dir: output/smac_mf/${dataset.name}/${trainer.configuration}/${smac_seed}
  job:
    chdir: true
