seed: 0
hyperparameters:
# Hyperparameter optimization (HPO) hyperparameters
  hp_config.optimizer:
    type: categorical
    choices:
      - SGD
      - Adam
      - AdamW
    default: SGD
  hp_config.momentum:
    type: uniform_float
    upper: 0.999
    lower: 0.5
    default: 0.99
    log: true
  hp_config.initial_lr:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-05
    default: 1.0e-02
    log: true
  hp_config.lr_scheduler:
    type: categorical
    choices:
      - PolyLRScheduler
      - CosineAnnealingLR
      - None
    default: PolyLRScheduler
  hp_config.weight_decay:
    type: uniform_float
    upper: 1.0e-02
    lower: 1.0e-06
    default: 3.0e-05
    log: true
  hp_config.oversample_foreground_percent:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default: 0.33
    log: false
  hp_config.loss_function:
    type: categorical
    choices:
      - DiceLoss
      - DiceAndCrossEntropyLoss
      - CrossEntropyLoss
      - TopKLoss
    default: DiceAndCrossEntropyLoss
  hp_config.aug_factor:
    type: uniform_float
    upper: 3.0
    lower: 0.0
    default: 1.0
    log: false
  hp_config.dropout_rate:
    type: uniform_float
    upper: 0.5
    lower: 0.0
    default: 0.2
    log: false
conditions:
  - child: hp_config.momentum
    parent: hp_config.optimizer
    value: SGD
    type: EQ
