# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

device: cuda

hydra:
  launcher:
    name: ${dataset.name}
    partition: kisski-inference
    gres: gpu:1
    gpus_per_task: 1
    cpus_per_task: 48
    mem_gb: 80
    timeout_min: 4320  # 3 days
    setup:
      - module load Miniforge3
      - module load CUDA/12.4.0
      - conda activate automis
      - export nnUNet_n_proc_DA=30
