# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: kisski-inference
    gres: gpu:1
    gpus_per_task: 1
    cpus_per_task: 48
    # exclude: gpu004.kisski
    # additional_parameters: 
    #   reservation: test
    mem_gb: 120
    timeout_min: 4320 # 3 days
    setup:
      - module load Miniconda3
      - module load CUDA
      - conda activate /mnt/home/jbecktep/.conda/envs/automis
      - export nnUNet_n_proc_DA=30
