# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

device: cuda

hydra:
  launcher:
    name: ${dataset.name}
    partition: kisski-inference
    gres: gpu:1
    gpus_per_task: 1
    cpus_per_task: 48
    mem_gb: 120
    timeout_min: 2880 # 2 days
    # additional_parameters:
    #   reservation: test5
    setup:
      - module load Miniforge3
      - module load CUDA
      - conda activate /mnt/home/jbecktep/.conda/envs/automis
      - export nnUNet_n_proc_DA=30
