# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ai,tnt
    gres: "gpu:1"
    timeout_min: 1 # 7200 # 5 days
    cpus_per_task: 32
    mem_gb: 128
    setup:
      - module load Miniforge3
      - module load CUDA
      - conda activate /bigwork/nhwpbecj/.conda/envs/unet
      - export CUDA_VISIBLE_DEVICES=0
      - export nnUNet_n_proc_DA=30
