# @package _global_
hp_config:
  aug_factor: 0.9204251788225997
  initial_lr: 0.003913922944854862
  loss_function: DiceAndCrossEntropyLoss
  lr_scheduler: PolyLRScheduler
  momentum: 0.9407396602426811
  num_epochs: 1000.0
  optimizer: SGD
  oversample_foreground_percent: 0.42018558228264713
  weight_decay: 0.00011468516553788085
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/hpo/Dataset009_Spleen/3d_fullres/0/incumbent
  sweep:
    dir: output/hpo/Dataset009_Spleen/3d_fullres/0/incumbent
    subdir: fold_${fold}
