# @package _global_
hp_config:
  aug_factor: 1.1497217957368147
  dropout_rate: 0.32393568431650144
  initial_lr: 0.005127304039850301
  loss_function: DiceAndCrossEntropyLoss
  lr_scheduler: CosineAnnealingLR
  momentum: 0.7992181565147479
  num_epochs: 333.3333333333333
  optimizer: SGD
  oversample_foreground_percent: 0.28202065079498606
  weight_decay: 1.5273452843961193e-05
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/hpo_hnas/Dataset001_BrainTumour/3d_fullres/0/incumbent
  sweep:
    dir: output/hpo_hnas/Dataset001_BrainTumour/3d_fullres/0/incumbent
    subdir: fold_${fold}
