# @package _global_
hp_config:
  aug_factor: 1.061679319629873
  initial_lr: 0.005146907561661071
  loss_function: DiceLoss
  lr_scheduler: CosineAnnealingLR
  momentum: 0.9662101191039068
  num_epochs: 1000.0
  optimizer: SGD
  oversample_foreground_percent: 0.4213858516709481
  weight_decay: 4.8197404429009124e-06
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/hpo/Dataset007_Pancreas/3d_fullres/0/incumbent
  sweep:
    dir: output/hpo/Dataset007_Pancreas/3d_fullres/0/incumbent
    subdir: fold_${fold}
