# @package _global_
hp_config:
  aug_factor: 1.0
  dropout_rate: 0.22405499782335475
  initial_lr: 0.0018739505174942747
  loss_function: TopKLoss
  lr_scheduler: PolyLRScheduler
  momentum: 0.9364525443926491
  num_epochs: 1000.0
  optimizer: SGD
  oversample_foreground_percent: 0.33
  weight_decay: 3.0e-05
hydra:
  job:
    chdir: true
  job_logging:
    stderr: true
    stdout: true
  output_subdir: "."
  run:
    dir: output/hpo_hnas/Dataset009_Spleen/3d_fullres/0/incumbent
  sweep:
    dir: output/hpo_hnas/Dataset009_Spleen/3d_fullres/0/incumbent
    subdir: fold_${fold}
